<a href="https://colab.research.google.com/github/Jayakrishna155/MachineLearning/blob/main/KfoldValidation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from seaborn import heatmap


In [8]:
iris = load_iris()
df = pd.DataFrame(iris.data,columns = iris.feature_names);
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [9]:
df['target'] = iris.target
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  target
0                5.1               3.5                1.4               0.2       0
1                4.9               3.0                1.4               0.2       0
2                4.7               3.2                1.3               0.2       0
3                4.6               3.1                1.5               0.2       0
4                5.0               3.6                1.4               0.2       0

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df.drop('target',axis=1),df.target,test_size=0.2)

In [11]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(x_train,y_train)
model.score(x_test,y_test)

0.9

In [12]:
from sklearn.svm import SVC
model = SVC()
model.fit(x_train,y_train)
model.score(x_test,y_test)

0.8666666666666667

In [13]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model.fit(x_train,y_train)
model.score(x_test,y_test)

0.8666666666666667

In [4]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [6]:
for train_i,test_i in kf.split([1,2,3,4,5,6,7,8,9]):
  print(train_i,test_i)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [27]:
def get_score(model,x_train,x_test,y_train,y_test):
  model.fit(x_train,y_train)
  return model.score(x_test,y_test)

In [82]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=5)

In [83]:
l_s = [];s_s=[];r_s=[]
for train_i, test_i in folds.split(df.drop('target', axis=1), df.target):
  x_train = df.drop('target', axis=1).iloc[train_i]
  x_test = df.drop('target', axis=1).iloc[test_i]
  y_train, y_test = df.target[train_i], df.target[test_i]

  l_s.append(get_score(LogisticRegression(), x_train, x_test, y_train, y_test))
  s_s.append(get_score(SVC(), x_train, x_test, y_train, y_test))
  r_s.append(get_score(RandomForestClassifier(n_estimators=50), x_train, x_test, y_train, y_test))

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [84]:
l_s


[0.9666666666666667, 1.0, 0.9333333333333333, 0.9666666666666667, 1.0]

In [85]:
  r_s

[0.9666666666666667, 0.9666666666666667, 0.9333333333333333, 0.9, 1.0]

In [93]:
s_s
import numpy as np

In [94]:
from sklearn.model_selection import cross_val_score
ls = cross_val_score(LogisticRegression(),df.drop('target',axis=1),df.target)
np.average(ls)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


np.float64(0.9733333333333334)

In [95]:
svs=cross_val_score(SVC(),df.drop('target',axis=1),df.target)
np.average(svs)

np.float64(0.9666666666666666)

In [96]:
rfs=cross_val_score(RandomForestClassifier(n_estimators=50),df.drop('target',axis=1),df.target )
np.average(rfs)

np.float64(0.9600000000000002)